name: Validate and process Building Block
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  validate-and-process:
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
